version: '3'

services:
  server:
    image: "kenutsunomiya/snacktrack-server:latest"
    hostname: server
    ports:
      - "80:5000"
    mem_limit: 128m
    environment:
      - PORT=$PORT
      - DB_DIALECT=$DB_DIALECT
      - DB_PROTOCOL=$DB_PROTOCOL
      - DB_USERID=$DB_USERID
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - CLIENT=$CLIENT
      